dailyfresh-master/dailyfresh-master/dailyfresh/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# from df_goods import search_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('df_user.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^goods/', include('df_goods.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('df_goods.urls', namespace='goods')),
    #url(r'^search/', search_views.MySeachView(), name='haystack_search'),
]

dailyfresh-master/dailyfresh-master/df_cart/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/19 15:35
# @Author  : Aries
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from df_cart import views


app_name = 'df_cart'
urlpatterns=[
    url(r'^$', views.cart),
    # 下面一行第一个(\d+)表示商品ID,第二个(\d+)表示商品数量
    url(r'^add(\d+)_(\d+)/$', views.add),
    url(r'^edit(\d+)_(\d+)/$', views.edit),
    url(r'^delete(\d+)/$', views.delete),
]

dailyfresh-master/dailyfresh-master/df_user/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# @Time    : 2018/2/18 17:57
# @Author  : Aries
# @Site    : 
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from . import views
app_name = 'df_user'
urlpatterns=[
    url(r'^register/$', views.register),
    url(r'^register_handle/$', views.register_handle),
    url(r'^register_exist/$', views.register_exist),
    url(r'^login_handle/$', views.login_handle),
    url(r'^login/$', views.login),
    url(r'^info/$', views.info),
    #url(r'^order/', views.order),
    url(r'^site/$', views.site),
    url(r'^logout/$', views.logout),
    url(r'^user_center_order&(\d+)/$', views.user_center_order),
]

dailyfresh-master/dailyfresh-master/df_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from df_user.models import UserInfo
# Create your models here.


class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey(UserInfo,  on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.IntegerField(default=0)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oaddress = models.CharField(max_length=150, default='')
    zhifu = models.IntegerField(default=0)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo', on_delete=models.CASCADE)
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE )
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.Integer Field()

dailyfresh-master/dailyfresh-master/df_user/models.py
# -*- coding: utf-8 -*-
# Create your models here.
from __future__ import unicode_literals
from django.db import models
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)

    #由于下面的属性没有添加到view函数中与数据库进行交互，而数据库中这几个属性值不允许为空，因此需要加上默认为空
    #收货人的名字
    ushou = models.CharField(max_length=20,default='')
    #收货地址
    uaddress = models.CharField(max_length=100,default='')
    uyoubian = models.CharField(max_length=6,default='')
    uphone = models.CharField(max_length=11,default='')

    #default和blank的更改是python层面的约束 不需要迁移，因为他们不影响数据库；
    #但是如果把default=''改为Null=True,表允许为空，虽然效果一样，但需要迁移数据库

dailyfresh-master/dailyfresh-master/df_user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from df_user.models import *
from hashlib import sha1
from django.http import JsonResponse
from .islogin import islogin
from df_goods.models import GoodsInfo
from df_order.models import OrderInfo
from django.core.paginator import Paginator
from df_cart.models import *


# Create your views here.
def register(request):
    return render(request, 'df_user/register.html')


# 登入处理，register.html的form表单中数据提交到的地方
def register_handle(requst):
    response = HttpResponse()

    # 接收用户输入，下面post.get()中的参数就是register.html中input表单的name属性值
    post = requst.POST

    uname = post.get('user_name')
    upwd = post.get('pwd')
    ucpwd = post.get('cpwd')
    uemail = post.get('email')

    #判断两次密码是否一致，虽然在js中判断过一次，这里最好也做一次判断
    if upwd != ucpwd:
        return redirect('/user/register/')

    #密码加密，需要引入hashlib模块
    s1 = sha1()
    # s1.update(upwd)  python 2.7这样进行加密处理
    #python3下字符串为Unicode类型，而hash传递时需要的是utf-8类型，需转换下
    s1.update(upwd.encode("utf-8"))
    #使用hexdiget()方法可以拿到加密后的结果
    upwd3 = s1.hexdigest()

    #创建模型类对象，以便和数据库交互
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    #存到数据库
    user.save()
    #注册成功就跳转到登陆页面
    return redirect('/user/login/')

# 判断用户是否已经存在
def register_exist(requset):
    #接收get方式传过来的数据
    uname = requset.GET.get('uname')
    #django模型查询，过滤出uname,后面加上count(),如果原先有这个用户就返回1，否则返回0
    #参考https://blog.csdn.net/u014745194/article/details/74612947
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})


# 登录界面
def login(request):
    uname = request.COOKIES.get('uname', '')#这个效果是从cookies中取出用户名放在显示页面
    context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname}
    return render(request, 'df_user/login.html', context)


# 登录处理
def login_handle(request):
    # 接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    #这里接收的参数'jizhu'为从login.html中接收的，默认为勾选了则为1，那么就不会用后面的默认值0
    jizhu = post.get('jizhu', 0)
    # 根据用户名查询对象，这里用filter，如果查不到会返回[]
    users = UserInfo.objects.filter(uname=uname)
    # print uname
    # 判断如果未查到则用户名错，查到再判断密码是否正确，正确则转到用户中心
    if len(users) == 1:
        s1 = sha1()
        s1.update(upwd.encode("utf-8"))
        #登录带cookie值   必须 red = HttpResponseRedirect    red.set_cookie  renturn red
        if s1.hexdigest() == users[0].upwd:
            red = HttpResponseRedirect('/user/info') #转到用户中心
            count = CartInfo.objects.filter(user_id=users[0].id).count()

            #另外一种写法
            #url = request.COOKIES.get('url', '/')  这里的'/'是默认值，表示url中没设定时，转到'/'
            #red=HttpResponseRedirect(url)


            # 记住用户名，就是如果选上记住用户名勾选框，就把用户名记在cookie中
            #set_cookie()是HttpResponse中的方法，而HttpResponseRedirect继承了HttpResponse.
            if jizhu != 0:
                red.set_cookie('uname', uname)

            #如果不勾选记住用户名，就把uname值清空，max_age=-1表示立即过期，
            else:
                red.set_cookie('uname', '', max_age=-1)

            #状态保持中的session存储方式的使用，对于使用频率比较高的数据可以使用
            #存储方式包括cookie、session，会话一般指session对象
            #使用cookie，所有数据存储在客户端，注意不要存储敏感信息
            #推荐使用sesison方式，所有数据存储在服务器端，在客户端cookie中存储session_id
            #状态保持的目的是在一段时间内跟踪请求者的状态，可以实现跨页面访问当前请求者的数据
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            request.session['count'] = count
            return red #记住最后必须return

        #这里表示密码不对的处理
        else:
            context = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname}
            return render(request, 'df_user/login.html', context)

    #这里表示没查到用户名，表明用户名错误，这里error_name设为1
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname }
        #error_name=1传到login.html中，在里面会对应的代码显示用户名错误
        return render(request, 'df_user/login.html', context)


# 登录用户中心
@islogin
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail

    #最近浏览，参考df_goods中的views.py
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_id_list = goods_ids.split(',')
    #按最近浏览顺序排列
    goods_list = []
    if len(goods_ids):
        for goods_id in goods_id_list:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context = {'title': '用户中心',
               'user_email': user_email,
               'user_name': request.session['user_name'],
               'page_name': 1,
               'info': 1,
               'goods_list': goods_list}
    return render(request, 'df_user/user_center_info.html', context)


# 订单
@islogin
def order(request):
    context = {'title': '用户中心','page_name':1,'order':1}
    return render(request, 'df_user/user_center_order.html', context)


# 收货地址
@islogin
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uphone = post.get('uphone')
        user.uyoubian = post.get('uyoubian')
        user.save()
    context = {'title': '用户中心', 'user': user, 'page_name': 1, 'site': 1}
    return render(request, 'df_user/user_center_site.html', context)


def logout(request):
    #退出时清除session，flush()：删除当前的会话数据并删除会话的Cookie
    request.session.flush()
    return redirect('/')


@islogin
def user_center_order(request, pageid):
    """
    此页面用户展示用户提交的订单，由购物车页面下单后转调过来，也可以从个人信息页面查看
    根据用户订单是否支付、下单顺序进行排序
    """

    uid = request.session.get('user_id')
    # 订单信息，根据是否支付、下单顺序进行排序
    orderinfos = OrderInfo.objects.filter(
        user_id=uid).order_by('zhifu', '-oid')

    # 分页
    #获取orderinfos list  以两个为一页的 list
    paginator = Paginator(orderinfos, 2)
    # 获取 上面集合的第 pageid 个 值
    orderlist = paginator.page(int(pageid))
    #获取一共多少 页
    plist = paginator.page_range
    #3页分页显示
    qian1 = 0
    hou = 0
    hou2 = 0
    qian2 = 0
    # dd = dangqian ye
    dd = int(pageid)
    lenn = len(plist)
    if dd>1:
        qian1 = dd-1
    if dd>=3:
        qian2 = dd-2
    if dd<lenn:
        hou = dd+1
    if dd+2<=lenn:
        hou2 = dd+2



    # 构造上下文
    context = {'page_name': 1,
               'title': '全部订单',
               'pageid': int(pageid),
               'order': 1,
               'orderlist': orderlist,
               'plist': plist,
               'pre': qian1,
               'next': hou,
               'pree': qian2,
               'lenn': lenn,
               'nextt': hou2}

    return render(request, 'df_user/user_center_order.html', context)

dailyfresh-master/dailyfresh-master/templates/df_user/base.html
{% extends 'base.html' %}
{% block body %}
<div class="main_con clearfix">
  <div class="left_menu_con clearfix">
  <h3>用户中心</h3>
  <ul>
    <li><a href="/user/info"{% if info %} class="active"{% endif %}>· 个人信息</a></li>
    <li><a href="/user/user_center_order&1/"{% if order %} class="active"{% endif %}>· 全部订单</a></li>
    <li><a href="/user/site"{% if site %} class="active"{% endif %}>· 收货地址</a></li>
  </ul>
  </div>
  {% block right_content %}
  {% endblock right_content %}
</div>
{% endblock body %}

dailyfresh-master/dailyfresh-master/templates/df_user/login.html
{% extends 'base_foot.html' %}
{% block head %}
    <script>
    $(function () {
        name_error=false
        pwd_error=false
        if($('.name_input').val().length!=0){
            name_error = true
        }
        if($('.pwd_error').val().length!=0){
            pwd_error = true
        }


        //对应views.py中的login_handle部分用户名错误的代码
        if({{ error_name }}== 1){
            $('.user_error').html('用户名错误').show();
        }
        if({{ error_pwd }}== 1){
            $('.pwd_error').html('密码错误').show()
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length==0){
                $('.user_error').html('请填写用户名').show();
                name_error=false;
            }else {
                $('.user_error').hide()
                name_error=true;
            }

        })
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length==0){
                $('.pwd_error').html('请写密码').show();
                pwd_error=false
            }
            else {$('.pwd_error').hide()
                pwd_error=true}
        })

        $(":submit[id=lo]").click(function(check){
            console.log(pwd_error,name_error)
        if(pwd_error==false || name_error==false){
           check.preventDefault();//此处阻止提交表单
        }
    });

    })
    </script>
{% endblock head %}
{% block body %}
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form id="form" action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
                            <!-- 这里默认值为1，加上后面的checked就是勾选上记住用户名；对应view.py中login_handle函数的设置 -->
							<input type="checkbox" name="jizhu" value="1" checked>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input id="lo" type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

dailyfresh-master/dailyfresh-master/templates/df_user/register.html
<!--//继承于base_foot.html页面-->
{% extends 'base_foot.html' %}

{% load static from staticfiles %}

<!--//注册按钮代码-->
{% block head %}
<script type="text/javascript" src="{% static  'js/register.js' %}"></script>
{% endblock head %}


{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">

                <!--//action中写入form表单要提交到的地方，register_handle需要在view函数中定义-->
				<form action="/user/register_handle/" id="reg_form" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>

                            <!--//只有设置了 name 属性的表单元素才能在提交表单时传递它们的值，一般和id值一致。-->
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <!-- checked="checked"中的值可以为任何值，也可以只写成checked,不要后面的值 -->
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input  type="submit" value="注 册" name="">
{#                            <button type="submit" value="注 册"></button>#}
                        </li>
                    </ul>
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

dailyfresh-master/dailyfresh-master/templates/df_user/user_center_info.html
{%extends 'df_user/base.html'%}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_email}}</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

				{%for goods  in goods_list%}
				<li>
					<a href="/{{goods.id}}"><img src="/static/{{goods.gpic}}"></a>
					<h4><a href="detail.html">{{goods.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{goods.gprice}}</span>
						<span class="unit">{{goods.gprice}}/{{goods.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{%endfor%}
			        </ul>
		        </div>
		</div>


{% endblock right_content %}

dailyfresh-master/dailyfresh-master/templates/df_user/user_center_order.html
{%extends 'df_user/base.html'%}
{% block right_content %}
<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    {% for orderinfo in orderlist %}
    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{orderinfo.odate}}</li>
        <li class="col02">订单号：{{orderinfo.oid}}</li>
        {% if orderinfo.zhifu == 1 %}
        <li class="col02 stress">已支付</li>
        {% else %}
        <li class="col02 stress">未支付</li>
        {% endif %}
    </ul>
    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                {% for item in orderinfo.orderdetailinfo_set.all %}
                <ul class="order_goods_list clearfix">
                    <li class="col01"><img src="/static/{{item.goods.gpic}}"></li>
                    <li class="col02">{{item.goods.gtitle}}<em><span>{{item.price}}</span>元/{{item.goods.gunit}}</em>
                    </li>
                    <li class="col03">{{item.count}}个</li>
                    <li class="col04"></li>
                </ul>
                {% endfor %}
            </td>
            <td width="15%">{{orderinfo.ototal}}元</td>
            {% if orderinfo.zhifu == 1 %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
            {% else %}
            <td width="15%">未付款</td>
            <td width="15%"><a href="/order/pay&{{orderinfo.oid}}/" class="oper_btn">去付款</a></td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    {% endfor %}
    <div class="pagenation">
        {% if orderlist.has_previous %}
        <a href="/user/user_center_order&{{orderlist.previous_page_number}}/">
            上一页
        </a>
        {% endif %}
{#    分页 ： plist 一共多少页  pageid 当前页  orderlist paginator按照两个一页，分的，页的指向对象  #}
    {% if lenn < 4  %}
        {% if lenn == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        {% elif lenn == 2 %}
            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% elif lenn == 3%}

            {% if pageid == 1 %}
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
            {% elif pageid == 2 %}
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
            {% else %}
            <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
            <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
            <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
            {% endif %}
        {% endif %}
    {% elif pageid < lenn %}
        {% if orderlist.has_previous  %}
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        {% else %}
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
        <a href="/user/user_center_order&{{next}}/" >{{next}}</a>
        <a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
        {% endif %}
    {% else %}
        <a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
        <a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
        <a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
    {% endif %}


        {% if orderlist.has_next %}
        <a href="/user/user_center_order&{{orderlist.next_page_number}}/">下一页></a>
        {% endif %}
    </div>
</div>


{%endblock right_content %}

dailyfresh-master/dailyfresh-master/templates/df_user/user_center_site.html
{%extends 'df_user/base.html'%}
{%block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} ({{user.ushou}} 收) 电话：{{user.uphone}} 邮编：{{user.uyoubian}} </dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{%csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{user.ushou}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{user.uaddress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{user.uyoubian}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{user.uphone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{%endblock right_content %}